repos:
   - repo: https://github.com/adamchainz/blacken-docs
     rev: "v1.12.1"
     hooks:
       - id: blacken-docs
         additional_dependencies:
         - black==22.12.0
   - repo: https://github.com/astral-sh/ruff-pre-commit
     # Ruff version.
     rev: v0.0.270
     hooks:
       - id: ruff
   - repo: https://github.com/PyCQA/autoflake
     rev: v2.1.1
     hooks:
       - id: autoflake
   - repo: https://github.com/pre-commit/pygrep-hooks
     rev: v1.10.0
     hooks:
       - id: python-use-type-annotations
   - repo: https://github.com/pycqa/flake8
     rev: 6.0.0
     hooks:
       - id: flake8
         additional_dependencies: [ flake8-annotations ]
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.4.0
     hooks:
       - id: check-merge-conflict
       - id: check-yaml
       - id: end-of-file-fixer
       - id: mixed-line-ending
