[tool.black]
line-length = 120

[tool.pycln]
all = true

[tool.pylint."messages control"]
disable = ["all"]
enable = [
    "abstract-method",
    "bad-staticmethod-argument",
    "consider-merging-isinstance",
    "function-redefined",
    "undefined-variable",
    "unused-private-member",
]

[tool.ruff]
# Configure the line-length so Ruff knows how long to make any lines it
# modifies.
line-length = 120
target-version = "py38"

select = ["F", "E", "EM"]

ignore = [

  "E501", # E501 line length (we use black auto-formatter to handle line length)
  "E741", #	ambiguous-variable-name
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.pydoclint]
style = 'google'
exclude = '\.git|\.tox|tests/.'
allow-init-docstring = true

[tool.hatch]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tecton-http-client-python"
description = "A Python Client for the Tecton Feature Service HTTP API"
requires-python = ">=3.8"
license = "Apache-2.0"
version = "0.0.1"



